# Generated by Django 4.2.1 on 2023-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExercisesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Strength", "Strength"),
                            ("Technique", "Technique"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
    ]
