# Generated by Django 4.2.1 on 2023-05-08 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExercisesModel",
            new_name="Exercises",
        ),
    ]
