# Generated by Django 4.2.1 on 2023-05-10 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0002_rename_exercisesmodel_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercises",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
